name: test-push

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.7
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: flake8 src --count --max-complexity=10 --max-line-length=127 --statistics --ignore E402
      - name: Run all tests
        env:
          GHE_TOKEN: ${{ github.token }}
        run: |
          cd tests
          python run_all_tests.py
